apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    svc: consumer-service
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
spec:
  ports:
    - port: 8080
      name: http-consumer
      targetPort: 8080
  selector:
    app: consumer-service

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-service-config
data:
  PORT: "8080"
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql/consumers
  SPRING_DATASOURCE_USERNAME: mysqluser
  SPRING_DATASOURCE_PASSWORD: mysqlpw
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  SPRING_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
  labels: 
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      name: consumer-service
      labels:
        app: consumer-service
        version: v1
    spec:
      containers:
        - image: consumer-service-kube
          name: consumer-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: consumer-service-config
