{
 "title": "Buisness",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "User registered",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "user_registered_count_total" }
   ]
  },
  {
   "title": "Registration Failure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "user_registered_failure_count_total"
    }
   ]
  },
  {
   "title": "Total login",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "login_count_total" }
   ]
  },
  {
   "title": "Login Failure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "login_failure_count_total" }
   ]
  },
  {
   "title": "Total Order V 1.0",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "order_count_total{version = \"v1\"}"
    }
   ]
  },
  {
   "title": "Total Order V 2.0",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "order_count_total{version = \"v2\"}"
    }
   ]
  },
  {
   "title": "Total cash V 1.0",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_cash_total{version = \"v1\"}"
    }
   ]
  },
  {
   "title": "Total cash V 2.0",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_cash_total{version = \"v2\"}"
    }
   ]
  },
  {
   "title": "Restaurant Menu Request V 1.0",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "restaurantMenu_request_total{version = \"v1\"}"
    }
   ]
  },
  {
   "title": "Restaurant Menu Request V 2.0",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "restaurantMenu_request_total{version = \"v2\"}"
    }
   ]
  }
 ]
}