version: '3'
services:
  ###    MYSQL   ####
  mysql:
      build: MySQL
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_USER=mysqluser
        - MYSQL_PASSWORD=mysqlpw
  iam:
      image: iam:latest
      ports:
        - 8080:8080
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/login
        SPRING_DATASOURCE_USERNAME: mysqluser
        SPRING_DATASOURCE_PASSWORD: mysqlpw
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
        # SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        # SPRING_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
        JAVA_OPTS: -Xmx192m 
