{
 "title": "Buisness",
 "time": { "from": "2019-07-11T12:45:20.494Z", "to": "2019-07-11T17:22:10.478Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total login",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "total_login_count_total" }
   ]
  },
  {
   "title": "User Registered",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "user_registered_count_total" }
   ]
  },
  {
   "title": "Registration failure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "user_registered_failure_count_total"
    }
   ]
  }
 ]
}