apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: efood-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - backend:
            serviceName: order-service
            servicePort: 8080
          path: /order-service/(.*)
        - backend:
            serviceName: kitchen-service
            servicePort: 8080 
          path: /kitchen-service/(.*)
        - backend:
            serviceName: consumer-service
            servicePort: 8080 
          path: /consumer-service/(.*)
        - backend:
            serviceName: restaurant-service
            servicePort: 8080
          path: /restaurant-service/(.*)
         