apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    svc: kafka-broker
spec:
  selector:
    role: broker
  ports:
    - port: 9092
      targetPort: 9092

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka-broker
data:
  KAFKA_ADVERTISED_HOST_NAME: kafka-broker
  KAFKA_ADVERTISED_PORT: "9092"
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_CREATE_TOPICS: "user-service-channel:1:1, consumer-service-channel:1:1,restaurant-service-channel:1:1,order-service-channel:1:1, kitchen-service-channel:1:1"
  KAFKA_ADVERTISED_LISTENERS: "INSIDE://:9092,OUTSIDE://kafka-broker:9094"
  KAFKA_LISTENERS: "INSIDE://:9092,OUTSIDE://:9094"
  KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka-broker
spec:
  serviceName: kafka-broker
  replicas: 1
  template:
    metadata:
      name: kafka-broker
      labels:
        role: broker
        app: kafka-broker
    spec:
      containers:
        - name: kafka-broker
          image: wurstmeister/kafka:latest
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config
