apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    svc: zookeeper
spec:
  selector:
    role: coordinator
  ports:
    - port: 2181
      targetPort: 2181

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  template:
    metadata:
      name: zookeeper
      labels:
        role: coordinator
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 2181
